[2025-05-12T13:59:46.273+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T13:59:46.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T13:59:46.281+0000] {logging_mixin.py:188} INFO - [2025-05-12T13:59:46.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T13:59:46.346+0000] {logging_mixin.py:188} INFO - [2025-05-12T13:59:46.339+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T13:59:46.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T13:59:46.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.197 seconds
[2025-05-12T14:00:16.555+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:00:16.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:00:16.559+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:00:16.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:00:16.585+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:00:16.580+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:00:16.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:00:16.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.069 seconds
[2025-05-12T14:00:46.877+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:00:46.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:00:46.881+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:00:46.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:00:46.917+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:00:46.912+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:00:46.919+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:00:46.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.080 seconds
[2025-05-12T14:01:54.421+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:01:54.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:01:54.427+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:01:54.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:01:54.462+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:01:54.457+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:01:54.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:01:54.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.091 seconds
[2025-05-12T14:02:24.757+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:02:24.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:02:24.761+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:02:24.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:02:24.786+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:02:24.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:02:24.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:02:25.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.468 seconds
[2025-05-12T14:02:55.506+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:02:55.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:02:55.512+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:02:55.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:02:55.546+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:02:55.539+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:02:55.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:02:55.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.109 seconds
[2025-05-12T14:03:25.832+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:03:25.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:03:25.836+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:03:25.836+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:03:25.869+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:03:25.863+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:03:25.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:03:25.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.166 seconds
[2025-05-12T14:03:56.531+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:03:56.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:03:56.543+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:03:56.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:03:56.611+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:03:56.601+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:03:56.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:03:56.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.272 seconds
[2025-05-12T14:04:27.116+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:04:27.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:04:27.121+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:04:27.120+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:04:27.146+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:04:27.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:04:27.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:04:27.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.085 seconds
[2025-05-12T14:04:57.491+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:04:57.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:04:57.495+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:04:57.494+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:04:57.522+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:04:57.517+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:04:57.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:04:57.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.067 seconds
[2025-05-12T14:05:27.786+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:05:27.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:05:27.789+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:05:27.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:05:27.816+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:05:27.811+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:05:27.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:05:27.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.060 seconds
[2025-05-12T14:05:58.069+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:05:58.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:05:58.073+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:05:58.072+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:05:58.094+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:05:58.090+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:05:58.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:05:58.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.055 seconds
[2025-05-12T14:06:28.273+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:06:28.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:06:28.276+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:06:28.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:06:28.299+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:06:28.294+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:06:28.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:06:28.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.056 seconds
[2025-05-12T14:06:58.514+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:06:58.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:06:58.517+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:06:58.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:06:58.540+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:06:58.535+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:06:58.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:06:58.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.061 seconds
[2025-05-12T14:07:28.749+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:07:28.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:07:28.752+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:07:28.751+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:07:28.777+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:07:28.771+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:07:28.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:07:28.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.065 seconds
[2025-05-12T14:07:58.948+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:07:58.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:07:58.950+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:07:58.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:07:58.974+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:07:58.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:07:58.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:07:59.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.058 seconds
[2025-05-12T14:08:29.268+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:08:29.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:08:29.271+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:08:29.271+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:08:29.295+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:08:29.291+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:08:29.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:08:29.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.058 seconds
[2025-05-12T14:08:59.779+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:08:59.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:08:59.782+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:08:59.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:08:59.802+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:08:59.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:08:59.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:08:59.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.052 seconds
[2025-05-12T14:09:30.160+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:09:30.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:09:30.163+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:09:30.162+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:09:30.188+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:09:30.183+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:09:30.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:09:30.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.058 seconds
[2025-05-12T14:10:00.549+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:10:00.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:10:00.551+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:10:00.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:10:00.577+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:10:00.572+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:10:00.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:10:00.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.059 seconds
[2025-05-12T14:10:30.930+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:10:30.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:10:30.932+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:10:30.932+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:10:30.953+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:10:30.949+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:10:30.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:10:30.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.052 seconds
[2025-05-12T14:11:01.137+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:11:01.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:11:01.140+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:11:01.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:11:01.163+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:11:01.158+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:11:01.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:11:01.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.059 seconds
[2025-05-12T14:11:31.341+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:11:31.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:11:31.344+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:11:31.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:11:31.366+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:11:31.363+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:11:31.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:11:31.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.063 seconds
[2025-05-12T14:12:01.600+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:12:01.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:12:01.604+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:12:01.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:12:01.628+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:12:01.623+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:12:01.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:12:01.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.074 seconds
[2025-05-12T14:12:32.014+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:12:32.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:12:32.756+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:12:32.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:12:32.785+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:12:32.780+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:12:32.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:12:32.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.818 seconds
[2025-05-12T14:13:03.121+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:13:03.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:13:03.124+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:13:03.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:13:03.149+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:13:03.145+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:13:03.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:13:03.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.067 seconds
[2025-05-12T14:13:33.352+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:13:33.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:13:33.356+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:13:33.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:13:33.377+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:13:33.373+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:13:33.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:13:33.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.059 seconds
[2025-05-12T14:14:03.679+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:14:03.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:14:03.682+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:14:03.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:14:03.707+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:14:03.701+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:14:03.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:14:03.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.058 seconds
[2025-05-12T14:14:33.955+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:14:33.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:14:33.958+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:14:33.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:14:33.979+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:14:33.975+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:14:33.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:14:34.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.059 seconds
[2025-05-12T14:15:04.355+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:15:04.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T14:15:04.358+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:15:04.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:15:04.384+0000] {logging_mixin.py:188} INFO - [2025-05-12T14:15:04.379+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T14:15:04.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T14:15:04.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.058 seconds
[2025-05-12T16:54:56.861+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:54:56.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:54:56.867+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:54:56.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:54:56.897+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:54:56.890+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:54:56.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:54:56.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.090 seconds
[2025-05-12T16:55:27.192+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:55:27.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:55:27.194+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:55:27.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:55:27.216+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:55:27.212+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:55:27.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:55:27.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.085 seconds
[2025-05-12T16:55:57.436+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:55:57.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:55:57.441+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:55:57.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:55:57.478+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:55:57.469+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:55:57.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:55:57.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.101 seconds
[2025-05-12T16:56:28.398+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:56:28.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:56:28.402+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:56:28.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:56:28.523+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:56:28.517+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:56:28.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:56:28.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.273 seconds
[2025-05-12T16:56:58.905+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:56:58.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:56:58.921+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:56:58.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:56:58.976+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:56:58.969+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:56:58.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:56:59.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.231 seconds
[2025-05-12T16:57:13.455+0000] {processor.py:161} INFO - Started process (PID=189) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:57:13.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:57:13.458+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:57:13.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:57:13.489+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:57:13.484+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:57:13.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:57:13.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.359 seconds
[2025-05-12T16:57:44.418+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:57:44.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:57:44.623+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:57:44.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:57:44.680+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:57:44.674+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:57:44.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:57:44.751+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.446 seconds
[2025-05-12T16:58:15.754+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:58:15.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:58:15.757+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:58:15.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:58:16.426+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:58:16.412+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:58:16.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:58:21.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 5.908 seconds
[2025-05-12T16:58:52.794+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:58:52.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:58:52.800+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:58:52.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:58:52.832+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:58:52.825+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:58:52.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:58:52.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.095 seconds
[2025-05-12T16:59:26.634+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:59:26.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:59:26.706+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:59:26.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:59:26.728+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:59:26.723+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:59:26.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:59:29.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 2.465 seconds
[2025-05-12T16:59:59.681+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:59:59.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T16:59:59.685+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:59:59.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:59:59.711+0000] {logging_mixin.py:188} INFO - [2025-05-12T16:59:59.706+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T16:59:59.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T16:59:59.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.087 seconds
[2025-05-12T17:00:29.927+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:00:29.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:00:29.932+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:00:29.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:00:29.964+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:00:29.958+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:00:29.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:00:30.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.112 seconds
[2025-05-12T17:01:00.235+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:01:00.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:01:00.239+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:01:00.239+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:01:00.270+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:01:00.263+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:01:00.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:01:00.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.083 seconds
[2025-05-12T17:01:30.515+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:01:30.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:01:30.519+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:01:30.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:01:30.542+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:01:30.538+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:01:30.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:01:30.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.077 seconds
[2025-05-12T17:02:01.452+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:02:01.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:02:01.456+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:02:01.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:02:01.483+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:02:01.478+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:02:01.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:02:01.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.091 seconds
[2025-05-12T17:02:31.700+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:02:31.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:02:31.704+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:02:31.703+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:02:31.732+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:02:31.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:02:31.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:02:31.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.074 seconds
[2025-05-12T17:03:02.011+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:03:02.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:03:02.013+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:03:02.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:03:02.065+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:03:02.055+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:03:02.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:03:02.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.109 seconds
[2025-05-12T17:03:32.294+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:03:32.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:03:32.297+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:03:32.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:03:32.323+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:03:32.318+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:03:32.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:03:32.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.067 seconds
[2025-05-12T17:04:02.613+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:04:02.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:04:02.616+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:04:02.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:04:02.640+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:04:02.636+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:04:02.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:04:02.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.065 seconds
[2025-05-12T17:04:32.826+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:04:32.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:04:32.829+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:04:32.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:04:32.857+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:04:32.852+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:04:32.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:04:32.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.070 seconds
[2025-05-12T17:05:03.242+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:05:03.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:05:03.246+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:05:03.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:05:03.272+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:05:03.267+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:05:03.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:05:03.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.066 seconds
[2025-05-12T17:05:33.451+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:05:33.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:05:33.455+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:05:33.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:05:33.480+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:05:33.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:05:33.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:05:33.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.059 seconds
[2025-05-12T17:06:03.736+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:06:03.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:06:03.739+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:06:03.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:06:03.763+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:06:03.758+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:06:03.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:06:03.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.076 seconds
[2025-05-12T17:06:33.993+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:06:33.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:06:33.995+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:06:33.995+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:06:34.025+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:06:34.018+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:06:34.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:06:34.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.071 seconds
[2025-05-12T17:07:04.277+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:07:04.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/nasdaq_report_dag.py for tasks to queue
[2025-05-12T17:07:04.281+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:07:04.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:07:04.309+0000] {logging_mixin.py:188} INFO - [2025-05-12T17:07:04.303+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/nasdaq_report_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/nasdaq_report_dag.py", line 6, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2025-05-12T17:07:04.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/nasdaq_report_dag.py
[2025-05-12T17:07:04.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/nasdaq_report_dag.py took 0.069 seconds
